#pragma once

#define NO_ICON     -1


namespace Imagine
{
    
    enum Icon
    {
        NEW_PROJECT,
        IMPORT_ASSET,
        OPEN_PROJECT,
        SAVE_PROJECT,
        SAVE_PROJECT_AS,
        EXPORT_MOVIE,
        EXPORT_IMAGE,
        VIEW_SECOND,
        SETTINGS,
        UNDO,
        REDO,
        PLAY,
        PAUSE,
        STOP,
        LOOP,
        BROWSE,
        DOWNLOAD_SKIN,
        IMPORT_FROM_WORLD,
        SPHERE,
        CUBE,
        BOX,
        CLOSE,
        CONTROLS,
        LIGHT,
        PARTICLES,
        VIEW_GRID,
        ASPECT_RATIO,
        RESET,
        LOOPS,
        SEARCH,
        GRID,
        SCALEALL,
        ADVANCED_COLORS,
        RELOAD,
        CHECK,
        ARROW_UP,
        ARROW_RIGHT,
        ARROW_DOWN,
        ARROW_LEFT,
        ARROW_UP_SMALL,
        ARROW_RIGHT_SMALL,
        ARROW_DOWN_SMALL,
        ARROW_LEFT_SMALL,
        ARROW_UP_TINY,
        ARROW_RIGHT_TINY,
        ARROW_DOWN_TINY,
        ARROW_LEFT_TINY,
        KEYFRAME,
        UNLOCK,
        LOCK,
        SHOW,
        HIDE,
        SOUND,
        MUTE,
        COLOR,
        COLOR_FRAME,
        CREATE,
        ANIMATE,
        COPY,
        PASTE,
        FOLDER_ADD,
        IMPORT,
        EXPORT,
        DUPLICATE_,
        REMOVE,
        WALK,
        RUN,
        COPY_KEYFRAMES,
        CUT_KEYFRAMES,
        PASTE_KEYFRAMES,
        REMOVE_KEYFRAMES,
        EXPORT_KEYFRAMES
    };

}
