#pragma once

#include <base.hpp>

#define TRUE_FUNC   []() { return true; }
#define FALSE_FUNC  []() { return false; }

#define CONTAINER_START_SIZE        380
#define CONTAINER_MIN_WIDTH         300
#define CONTAINER_MIN_HEIGHT        30
#define CONTAINER_INSERT_SIZE       50
#define CONTAINER_RESIZE_BOX_SIZE   20

#define TAB_CONTENT_PADDING     8
#define TAB_CONTENT_MIN_WIDTH   300
#define TAB_CONTENT_MAX_WIDTH   500
#define TAB_SELECT_HEIGHT       30

#define CONTROL_MARGIN_RIGHT    2
#define CONTROL_MARGIN_LEFT     2
#define CONTROL_MARGIN_BOTTOM   8
#define SCROLLBAR_SIZE          12
#define SCROLLBAR_MIN_SIZE      5
#define TEXTBOX_BOX_PADDING     4

#define VIEW_HEADER_HEIGHT      24

#define SETTING_INTERFACE_COLOR_MAIN                Color(19, 19, 19)
#define SETTING_INTERFACE_COLOR_BACKGROUND          SETTING_INTERFACE_COLOR_MAIN * Color(0.75f)
#define SETTING_INTERFACE_COLOR_TEXT                Color(160, 160, 160)
#define SETTING_INTERFACE_COLOR_BUTTONS             Color(10,10,10)
#define SETTING_INTERFACE_COLOR_BUTTONS_PRESSED     SETTING_INTERFACE_COLOR_BUTTONS * Color(0.75f)
#define SETTING_INTERFACE_COLOR_BUTTONS_TEXT        COLOR_WHITE
#define SETTING_INTERFACE_COLOR_BOXES               SETTING_INTERFACE_COLOR_BACKGROUND
#define SETTING_INTERFACE_COLOR_BOXES_PRESSED       SETTING_INTERFACE_COLOR_BOXES * Color(0.75f)
#define SETTING_INTERFACE_COLOR_BOXES_TEXT          SETTING_INTERFACE_COLOR_TEXT
#define SETTING_INTERFACE_COLOR_HIGHLIGHT           Color(132, 159, 204)
#define SETTING_INTERFACE_COLOR_HIGHLIGHT_TEXT      COLOR_WHITE