#pragma once

#include "base.hpp"
using namespace Base;

#define SETTING_INTERFACE_COLOR_MAIN                Color(200, 200, 200)
#define SETTING_INTERFACE_COLOR_TEXT                Color(10, 10, 10)
#define SETTING_INTERFACE_COLOR_BUTTONS             Color(67,103,163)
#define SETTING_INTERFACE_COLOR_BUTTONS_PRESSED     SETTING_INTERFACE_COLOR_BUTTONS * Color(0.9f)
#define SETTING_INTERFACE_COLOR_BUTTONS_TEXT        COLOR_WHITE
#define SETTING_INTERFACE_COLOR_BOXES               COLOR_WHITE
#define SETTING_INTERFACE_COLOR_BOXES_PRESSED       SETTING_INTERFACE_COLOR_BOXES * Color(0.9f)
#define SETTING_INTERFACE_COLOR_BOXES_TEXT          SETTING_INTERFACE_COLOR_TEXT
#define SETTING_INTERFACE_COLOR_HIGHLIGHT           Color(132, 159, 204)
#define SETTING_INTERFACE_COLOR_HIGHLIGHT_TEXT      COLOR_WHITE